python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=True --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=False --smote=True --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=False --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=False --adasyn=True --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=False --adasyn=False --smote=True --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=False --adasyn=False --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=True --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=False --smote=True --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=False --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=False --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=True --smote=False --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=False --smote=True --ros=False;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=False --smote=False --ros=True;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=False --smote=False --ros=True;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=False --smote=False --ros=True;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=False --smote=False --ros=True --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=True --adasyn=False --smote=False --ros=False --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=False --smote=False --ros=True --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=True --pca=False --adasyn=False --smote=False --ros=False --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=True --adasyn=False --smote=False --ros=False --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=False --smote=False --ros=True --feat=True;
python -m fire preprocessing_search train_and_evaluate --log=False --pca=False --adasyn=False --smote=False --ros=False --feat=True;